### ISSUE TITLE
Handle array JSON without key

### ISSUE THREAD

**Issue by abhishekvk** [sucom/SPA.js#1]
I have a data-url which simply returns an integer array: [1,2,3,4,5]. This is a valid JSON and needs to be displayed in HTML. With handlebars we can use {{#each this}} but that does not work when done through SPA. I have to use the callback and then later render the data. A way to render such data needs to be provided. Maybe a data-wrap="numarray" which will wrap the JSON like {numarray:[1,2,3,4,5]} could be provided. Now in template {{#each numarray}} can be done,

**Comment by sucom** [comment]
Good one. I will address this in the upcoming release.

**Comment by sucom** [comment]
Fixed. Try with release v2.16.0
