### ISSUE TITLE
Using ES6 Modules From Components

### ISSUE THREAD

**Issue by alxAgu** [sucom/SPA.js#10]
Is there a recommended structure (or is it even possible) to import es6 modules from components?

**Comment by sucom** [comment]
Thanks @alxAgu for the query.

Currently it does not support importing ES6 modules using component configuration.

However, it seems to be interesting one to consider. Could you please elaborate your request with the use case and examples.

Thanks

**Comment by sucom** [comment]
Interestingly,

SPA.js component has an option to load other javascripts using scripts property. (sorry missed to document in the website. we will update the site soon). In the mean while, you can try this with below example to include javascripts.

`
//--componentX.js--

spa.$('componentX', {
  target: '#targetContainer',
  ...
  scripts: [ './additional-script1.js', './additional-script2.js' ]
  ...
  ...
});

index.html (file)
app (folder)
    components (folder)
        componentX (folder)
            componentX.html (file)
            componentX.js (file)
            additional-script1.js (file)
            additional-script2.js (file)
        componentY (folder)
            ...
`
using the scripts property, it is possible to load external libraries, scripts.

NOTE: the path begins with ./ refers to it's components folder. It's possible to load scripts from other folders as well with reference to index.html or full external path.

Please check it out and let us know.

Thanks

**Comment by sucom** [comment]
Check out component's base property: [scripts](https://spa.js.org/#getStarted/extScripts)

If this does not solve your requirement, please explain your use case with examples.

Thanks

**Comment by alxAgu** [comment]
@sucom, thanks, that might work as well.

I'll give it a try over the weekend and will let you know.

**Comment by sucom** [comment]
Hi @alxAgu, Just updated the documentation for [ES6 module usage guide](https://spa.js.org/#getStarted/extModules) in SPA.js.

Hope this helps.

Thanks.

**Comment by sucom** [comment]
Hi @alxAgu. I hope all is well at your end and hope you got a chance to look at the documentation and examples. If you need any help/support, please feel free to submit your query.

Thanks.

**Comment by sucom** [comment]
Hi @alxAgu , I Hope you are safe and doing well. Check out the latest v2.84.0 for the full support of ES6 modules. You can also refer to the documentation (and download examples) at spa [site](https://spa.js.org/#getStarted/extModules).
