### ISSUE TITLE
ionic

### ISSUE THREAD

**Issue by mramizal** [sucom/SPA.js#11]
hi! is it possible to use ionic component in spajs? thanks

**Comment by sucom** [comment]
The team has not tried or experimented with it. However, any pure HTML, CSS and javascript components (like Bootstrap, Foundation, etc.) may be customized to fit within SPA.js framework.

**Comment by sucom** [comment]
Yes. It is working with [ionic-framework](https://ionicframework.com/docs/). you can download the basic boiler plate on Action Sheet [here](https://spa.js.org/spa-examples_cdn/ionic+spa.zip)

Thanks.

**Comment by mramizal** [comment]
i have tested your sample.. great!! it's working.. maybe i need to explore further why my header does not show the back button and side menu button, when i added it to your sample. it puzzled me, since it is working if using angular.
<ion-header>
    <ion-toolbar color="primary">
        <ion-buttons slot="start">
            <ion-back-button icon="arrow-back-circle-outline"></ion-back-button>
        </ion-buttons>
        <ion-title>MyApp</ion-title>
        <ion-thumbnail style="width:40px;height:40px;margin-right:5px" slot="end">
            <ion-img src="img/logo.png"></ion-img>
        </ion-thumbnail>
 
        <ion-buttons slot="start">
            <ion-menu-button autoHide="false"></ion-menu-button>
        </ion-buttons>
    </ion-toolbar>
</ion-header>

**Comment by sucom** [comment]
Good to know it works.

Added another example to show/hide menu. Check it out this [sample](https://spa.js.org/spa-examples_cdn/ionic+spa-ex-02-menu.zip).

Use [Feedback/Contact](https://spa.js.org/#getStarted/feedback) form for free support.

Thanks,

**Comment by mramizal** [comment]
wow! how u did that? i've been trying to use the slide menu before with no success. now i am trying to understand your spajs on how it build the ionic template on the page. it just missing the css i set on it.. for example image on the ion-content with class background and icon did not styled properly. i put the css in the appRoot.css
```

 <ion-menu side="start" content-id="main-content">
     <ion-header>
       <ion-toolbar translucent>
         <ion-title>Menu</ion-title>
       </ion-toolbar>
     </ion-header>
     <ion-content>
       <ion-list>
         <ion-item>
           <ion-icon name="mail" slot="start"></ion-icon>
          <ion-label>Inbox</ion-label>
         </ion-item>
         <ion-item>
           <ion-icon name="paper-plane" slot="start"></ion-icon>
           <ion-label>Outbox</ion-label>
         </ion-item>
       </ion-list>
     </ion-content>
   </ion-menu>
   
   
 <div class="ion-page" id="main-content">
     <ion-header>
         <ion-toolbar color="primary">
             <ion-buttons slot="start">
                 <ion-menu-button></ion-menu-button>
             </ion-buttons>
             <ion-title>MyApp</ion-title>
             <ion-thumbnail style="width:40px;height:40px;margin-right:5px" slot="end">
                 <ion-img src="img/logo.png"></ion-img>
             </ion-thumbnail>
         </ion-toolbar>
     </ion-header>
 
     <ion-content fullscreen class="background ion-padding">
         <div class="center-me">
             <section class="ion-text-center" margin-bottom>
                 <ion-icon style="color:white;" name="person-outline"></ion-icon>
                 <h3 style="color:white;font-size:1.4em" no-margin>Welcome, <br> Mr. John Doe</h3>
             </section>
             <ion-grid>
                 <ion-row>
                     <ion-col col-6>
                         <ion-card  class="ion-text-center" color="primary">
                             <ion-icon style="margin-top:20px" name="document-text-outline"></ion-icon>
                             <div style="margin-bottom:20px">New</div>                         </ion-card>
                     </ion-col>
                     <ion-col col-6>
                         <ion-card  class="ion-text-center" color="primary">
                             <ion-icon style="margin-top:20px" name="layers-outline"></ion-icon>
                             <div style="margin-bottom:20px">Update</div>
                       </ion-card>
                     </ion-col>
                </ion-row>
             </ion-grid>
         </div>
         </ion-content>
 </div>
 
 css
  ion-icon {
     font-size: 3.5em;
 }
 

  ion-content.background{
    --background: url(../img/bg.jpg);
}

```

**Comment by sucom** [comment]
As a best practice, it is recommended to load all app level common css (minified) and loaded in **index.html**. However, if you prefer to define and load **component-specific** css in run time, refer the following options.

---
_Option-1 (recommended)_: using [_style property](https://spa.js.org/#getStarted/style) in **componentX.js** along with **componentX.css**. To maintain HTML and CSS in separate files.

**componentX.html**: no css definition in html
```
<ion-content id="componentX-container">

  HTML content

</ion-content>
```

**componentX.css**: component specific css definitions
```
#componentX-container {
  background: ...
}
```

**componentX.js**: us `_style` property to load **componentX.css** along with **componentX.html**
```
import { ... ... } from '... ... ..'; // module imports if any

var _style = '.'; // this statement loads componentX.css

// other properties and functions ...

...

```

---
_Option-2_: in **componentX.html** using `style` tag for inline styles

```
<ion-content>
  HTML content goes here...
</ion-content>

<style>
  define component specific css properties here...
</style>
```

---

_Option-3_: in **componentX.html** using `<link>` tag to load external css file(s)

```
<div>
  HTML content
</div>

<link rel="stylesheet" href="relative/path/from/index.html/style.css">
```
---
Hope this helps.

**Comment by sucom** [comment]
Check out the working example [here](https://spa.js.org/spa-examples_cdn/ionic+spa-ex-03-css.zip).

Hope this helps to speed up your work.

**Comment by sucom** [comment]
Check out the ionic+spa boilerplate [here](https://spa.js.org/spa-examples_cdn/ionic+spa-boilerplate.zip).

Happy coding in SPA with ionic :-)

**Comment by mramizal** [comment]
superb! great example.
