### ISSUE TITLE
QUESTION : NOT WORKING FOR CORDOVA ?

### ISSUE THREAD

**Issue by cyrilxx** [sucom/SPA.js#12]
Is this really not working if use for cordova applications ?

**Comment by FrontEndNeo** [comment]
It is working with cordova so far. Please share more info on your issue.

If it's OK, you can contact via spajsorg(at)gmail(dot)com

Thanks

**Comment by cyrilxx** [comment]
I have a custom html template written in pure css and jquery. after adding the spa.js some functions of my template does not work anymore. 

My Template work just fine if im using javascript and jquery only. So I want to convert it to SPA but after adding it, it breaks my template

**Comment by sucom** [comment]
Could you please share the sample template of yours? If your template has handlebars syntax with double curly braces, then it must follow handlebars' rules. I fear that may be an issue. SPA is dependent on Handlebars.

**Comment by sucom** [comment]
Alternatively, if you don't want to use SPA's data binding, API modules etc. you could try simple SPA for HTML and javascript using the [alt-iframe](https://github.com/FrontEndNeo/alt-iframe) library.

**Comment by sucom** [comment]
Hi @cyrilxx, I hope the issue is resolved.

**Comment by sucom** [comment]
Hi @cyrilxx. We have not received any response from you. You can refer to the working example bundle [here](https://spa.js.org/spa-examples_cdn/cordova+spa-20210325-152727.zip)

Thanks
