### ISSUE TITLE
Need Demo :)

### ISSUE THREAD

**Issue by Uranbold** [sucom/SPA.js#2]
Hello,

We need more example Demo at least 2 :)

Thanks.

**Comment by sucom** [comment]
Thanks for your interest in SPAjs. The [YouTube Channel](https://www.youtube.com/channel/UCe6L_1hMBelR9-yc8wUgyqg/) is WIP and will be live soon.

**Comment by sucom** [comment]
For SPAjs examples please watch [GitHub Example Repo](https://github.com/spajsorg/spajs-examples).

YouTube playlist [Get Started](https://www.youtube.com/playlist?list=PLs3-BpNdJUuQi9qQEMyVoCBnu5hysqAaw) has been created for easy learning (more videos are coming soon).

Also, the [YouTube Channel](https://www.youtube.com/channel/UCe6L_1hMBelR9-yc8wUgyqg/) is WIP and will be live soon.

Meanwhile, use these examples:

- [SPA with cdn](https://spa.js.org/spa-examples_cdn/ex001-spa-basic-folder-struct+cdn.zip)
- [Data Scope](https://spa.js.org/spa-examples_cdn/ex002-spa-basic-template+data-scope.zip)
- [If Helper](https://spa.js.org/spa-examples_cdn/ex004-spa-basic-template-helper-if.zip)
- [Advanced Each Helper](https://spa.js.org/spa-examples_cdn/ex006-spa-basic-template-helper-each+advanced.zip)
- [Custom Helpers](https://spa.js.org/spa-examples_cdn/ex003-spa-basic-template-helper-custom.zip)
- [Form Select Options Builder Helper](https://spa.js.org/spa-examples_cdn/ex007-spa-basic-template-helper-form-select-options.zip)
- [Form element Helpers](https://spa.js.org/spa-examples_cdn/ex008-spa-basic-template-helper-form-element-state.zip)

Thanks,
SPAjs Team

**Comment by sucom** [comment]
For SPAjs specific Examples, please watch [Example Repo](https://github.com/spajsorg/spajs-examples).

YouTube playlist [Get Started](https://www.youtube.com/playlist?list=PLs3-BpNdJUuQi9qQEMyVoCBnu5hysqAaw) has been created for easy learning (more videos are coming soon).

Also, the [YouTube Channel](https://www.youtube.com/channel/UCe6L_1hMBelR9-yc8wUgyqg/) is WIP and will be live soon.

Meanwhile, use these examples:

- [SPA with cdn](https://spa.js.org/spa-examples_cdn/ex001-spa-basic-folder-struct+cdn.zip)
- [Data Scope](https://spa.js.org/spa-examples_cdn/ex002-spa-basic-template+data-scope.zip)
- [If Helper](https://spa.js.org/spa-examples_cdn/ex004-spa-basic-template-helper-if.zip)
- [Advanced Each Helper](https://spa.js.org/spa-examples_cdn/ex006-spa-basic-template-helper-each+advanced.zip)
- [Custom Helpers](https://spa.js.org/spa-examples_cdn/ex003-spa-basic-template-helper-custom.zip)
- [Form Select Options Builder Helper](https://spa.js.org/spa-examples_cdn/ex007-spa-basic-template-helper-form-select-options.zip)
- [Form element Helpers](https://spa.js.org/spa-examples_cdn/ex008-spa-basic-template-helper-form-element-state.zip)

Thanks,
SPAjs Team

**Comment by sucom** [comment]
Thank you for your interest in SPAjs.

For SPAjs specific Examples, please watch [Example Repo](https://github.com/spajsorg/spajs-examples).

YouTube [Get Started Playlist](https://www.youtube.com/playlist?list=PLs3-BpNdJUuQi9qQEMyVoCBnu5hysqAaw)  has been created for easy learning (more videos are coming soon).

Also, the YouTube [SPAjs Channel](https://www.youtube.com/channel/UCe6L_1hMBelR9-yc8wUgyqg) is WIP.

Hope this helps.

Thanks,
SPAjs Team
