### ISSUE TITLE
MYSQL data

### ISSUE THREAD

**Issue by covecove1** [sucom/SPA.js#5]
Hello,
considering that DB is MYSQL:

How can I make 2 divs (COMPONENTS) this way: 
First div show users from table 'users', 
Second div show orders from table 'orders' (FK user_id) FOR CURRENT USER on which we click in first div?

How to use custom SQL statements and WHERE conditions for our divs?

Thanks in advance!

**Comment by sucom** [comment]
Hi, Thanks for writing your query.

We would recommend you to see the examples at [Examples Repo](https://github.com/spajsorg/spajs-examples). Specifically the spajs-phonebook.

It's not clear about your question on usage of SQL statements and WHERE conditions in divs.

The SQL Statements to be used at the backend and only through API's the data will be brought to the front-end.

Hope this helps.

Regards,
SPAjs Team.
