### ISSUE TITLE
Async ajax & placeholder template

### ISSUE THREAD

**Issue by alxAgu** [sucom/SPA.js#6]
Hi, is there any way to render something while an ajax request is taking place?

In the component's js file I have the following:
```
spa.$('componentX', {
	target: '#container',
	dataUrl: '/user/{id}/profile',
	dataUrlParams: { id: '12345' }
});
```

I want to:
1) Make the request to '/user/12345/profile' async
2) Render something else while the request is taking place (e.g. a placeholder with a loading animation)

Can it be done? 

Thanks,

A.

**Comment by sucom** [comment]
Done. Use the latest spa version v2.67.0

Refer: Component's base property [dataPreRequest](https://spa.js.org/#getStarted/externalApiDataPreRequest) for usage.

Hope this helps.

Thanks.

**Comment by alxAgu** [comment]
@sucom, you are awesome! thanks mate. Will have a look this week 👍

**Comment by uXperienceLive** [comment]
@alxAgu, you are welcome. Happy to do any stuff that makes the engineer's life simple :-)

**Comment by sucom** [comment]
@alxAgu, you are welcome. Happy to do stuff that makes engineer's life simple :-)
