### ISSUE TITLE
Internationalization attributes with spaces

### ISSUE THREAD

**Issue by alxAgu** [sucom/SPA.js#7]
I'm trying to apply a lang-text to an attribute name that contains dashes "-":

`<div data-i18n="my-custom-attr:'navigation.menuitem.value'">Click Me</div>`

But I get the following error:
![image](https://user-images.githubusercontent.com/2165454/65598337-88101580-dfde-11e9-901b-074189498a6d.png)

Is there any way to do this?

Thanks.

**Comment by sucom** [comment]
Hi @alxAgu , thanks for trying out. data-18n value is a json. currently within SPA.js we don't support dash in json key. may be try enclosing the dashed key with single quote.

`<div data-i18n="'my-custom-attr':'navigation.menuitem.value'">Click Me</div>`

will wait for your response.

Thanks

**Comment by alxAgu** [comment]
@sucom, thanks. It worked!
