### ISSUE TITLE
Components In Sub-folders

### ISSUE THREAD

**Issue by alxAgu** [sucom/SPA.js#8]
Is there any way to have components in sub-folders? Eg:

 - **ComponentX**
   - ComponentX.html
   - ComponentX.js
   - **ComponentX-Feature1** 
       - ComponentX-Feature1.html
       - ComponentX-Feature1.html
   - **ComponentX-Feature2** 
       - ComponentX-Feature2.html
       - ComponentX-Feature2.html
   
Thanks.

**Comment by sucom** [comment]
Noop. Not in the current version. The team wanted to keep it simple. Nesting the components inside will lead to confusion as many developers will nest multi-level and make a mess and will be difficult for future developers.

**Comment by sucom** [comment]
Hi @alxAgu, there is an upcoming webinar you might be interested in.

[Rapid SPA](https://uxperience.live/webinar/opensourceforu)

Looking forward to see you there.

Thanks

**Comment by sucom** [comment]
Let us know the strong reasons for it or difficulties in keeping it under app/components folder. May be will consider in future release (not guaranteed though).

**Comment by sucom** [comment]
Hi @alxAgu . the team had a discussion and came to the conclusion that it is not possible to have components in sub folder.

As you know the components are registered under app as app.componentX. so we can not have dash in component Name which will be difficult to refer in javascript as app.componentX-feature1 (will be considered as minus operation).

Assuming that 

ComponentX
  - ComponentX.html
  - ComponentX.js
  * Feature1
     - Feature1.html
     - Feature1.js

and in componentX.js
if someone unknowingly add some property with same component name like below...

spa.$('componentX', {
  Feature1: { ... }
 });

and in Feature1.js

spa.$('Feature1', { ... }); 

this will overwrite Feature1 property defined earlier in componentX

It will create too much confusion and conflicts. So, we will not be able to implement in the current version. However, the team is working on next version 3.x from the ground-up and will consider this feature request.

Thanks for your support.

~SPA Team

**Comment by alxAgu** [comment]
@sucom, thank you for the responses. I missed the webinar but will make sure to check the recording (if there is one).

I understand the need for keeping the framework simple and I support the commitment to this cause. There are however some instances where you need a structured way to organise your components to avoid confusion.

Imagine you are building a CRM application that has, Customers, Organisations, Locations and other main modules. Both Customers and Organisations need 'list' views to display a list of customers and organisations and inner views to display the module's profile (member profile and organisation profile).

Because of the nature of the entities, both 'list' and 'profile' are unique views that will contain a different set of sub-components to represent all the attributes for that module. Eg. The 'list' component for **customers** would show attributes 'age' and 'email', while the **list** for the **organisation** would show 'address', and 'number of employees'. The same logic applies to the 'profile' subviews which would be a view that renders a number of individual components that are only relevant to each entity.

Unless I'm missing something, with the current version of the framework you are forced to have something like this:

- components
  - customerList
  - customerProfile
  - customerProfileWidget1
  - customerProfileWidget2
  - organisationList
  - organisationProfile
  - organisationProfileWidgetA
  - organisationProfileWidgetB

Which is rather confusing if you have 10 or more widgets/components per module. Instead, having the ability to group your components into folders will help you understand the structure of the system and see how components relate to each other in a more natural way:

- components
   - customer
      - list
      - profile
         - widget1
         - widget2
   - organisation
      - list
      - profile
         - widgetA
         - widgetB

With the above structure, future programers will know at a glance that 'widgetA' is only relevant to the 'organisation' module and also that it is only used as a sub-component of 'profile'.

I haven't really dived into the SPA.js code so I can't really comment on the implementation, but I firmly believe subfolders need to make their way into v3. 

Thank you all for working on this framework. It's the only one I've found so far that gets you started in 5 min with a minimum learning curve.

**Comment by sucom** [comment]
Hi @alxAgu. Thank you so much for taking your time to explain the requirement. You are truly inspiring and raising the bar to improve SPA.js. It's not impossible to implement sub-components in 2.x. We were able to convince 100+ application architects to stay with single level. However, I would like to talk to you offline outside this thread. So that we can implement it in a right way in 2.x itself or in 3.x. Request you to use the feedback form in spa.js.org site or drop in a mail to spajs.org@gmail.com 

We will post the webinar recording in our YouTube Channel as well as replace the same registration link with the recording next week.

Looking forward to collaborate to simplify the complex tasks.

Thanks again

~SPA Team

**Comment by sucom** [comment]
Hi @alxAgu. Done. Now in [v2.71.0-RC1](https://github.com/sucom/SPA.js/releases) you can create sub-components the way you described.

Also, updated the VS Code Extension [spajs](https://marketplace.visualstudio.com/items?itemName=spajs.spajs) as well as the npm package [spa-cli](https://www.npmjs.com/package/spa-cli)

1. You can manually create sub-folders the way you have described.

2. In componentX.js, define the path of the component (the path after app/components folder) with slash(/) as path separator, like the example below.
spa.$('**customer/list**', { ... });

this will register the component in app scope using a single name replacing / with _ as
app.**customer_list**
app.**organisation_profile_widgetA**
So, you can access/reference a sub component with single word using _ delimiter.

you can render the component with path notation as
spa.$render('**customer/list**', { ... }) with overriding params
or 
spa.$render('**customer/list**') without params

Also, you can create the components using spa-cli
inside the app folder
CMD> **spa-cli . _customer/profile/widget1_**
will create nested folders with sample code snippets for css, html and js

OR if you have installed vs-code extension "spajs". then
In a empty componentX.js file type spa$[tab] which will automatically fill the basic code snippet for that component with componentPath and componentAccessName

Please use the RC version for now and let us know how does it work for you. Even we have to test in all our apps for the compatibility.

Hope this helps.

Once again, thanks for your support.

~SPAjs Team

NOTE: The webinar recording is available at [vimeo](https://vimeo.com/370457250). You need to skip the first 10 min as the facilitator started the recording much earlier and did not edit before posting. I will edit (make it two parts 30 min each) and upload in our YouTube channel (next weekend task).

**Comment by sucom** [comment]
Hi @alxAgu, forgot to mention the new specification to render nested components in HTML.

**To render normal componentX**
- using _<spa-component>_ tag
`<spa-component src="componentX"></spa-component>`

- using _[data-spa-component]_ attribute
`<div data-spa-component="componentX"></div>`

**To renders nested component** 
_(prefix component path with $, else it will try to load server-side rendered component)_
- using _<spa-component>_ tag
`<spa-component src="$customer/profile/widget1"></spa-component>`

- using _[data-spa-component]_ attribute
`<div data-spa-component="$customer/profile/widget1"></div>`

~SPA Team

**Comment by alxAgu** [comment]
@sucom, you're a legend! Thank you guys! I haven't had a chance to check the update but will test it by all means this week. Appreciate the great work! 

Thanks again.

A.

**Comment by sucom** [comment]
Thanks @alxAgu. "Legend" is a big word. We are just doing what we know and what we can do. It's a great feeling of completeness/satisfaction to know that our work is useful to someone else.

Thanks for the motivation.

~SPA Team
